version: '3.8'

services:
  web:
    build:
      context: ./source/.
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./source/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.1-alpine
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=boiler
      - POSTGRES_PASSWORD=boilerplatepass
      - POSTGRES_DB=boiler_db
  celery:
    build: ./source/.
    command: celery -A project worker -l INFO
    volumes:
      - ./source:/usr/src/app
    env_file:
      - .env.dev
    depends_on:
      - web
      - db
      - redis
  celery-beat:
    build: source
    command: celery -A project beat -l info
    volumes:
      - ./source:/usr/src/app/
    env_file:
      - .env.dev
    depends_on:
      - redis
  redis:
    image: "redis:alpine"

volumes:
  postgres_data: null
