version: '3.8'

services:
  web:
    build:
      context: ./source/
      dockerfile: ./Dockerfile.prod
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:14.1-alpine
    volumes:
      - pg_vol:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  celery:
    build: ./source/
    command: celery -A project worker -l INFO
    volumes:
      - ./source/:/usr/src/app
    env_file:
      - .env.prod
    depends_on:
      - web
      - db
      - redis
  celery-beat:
    build: ./source/
    command: celery -A project beat -l info
    volumes:
      - ./source/:/usr/src/app/
    env_file:
      - .env.prod
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  pg_vol:
    external: true
    name: pg_vol
  static_volume: 
