# Generated by Django 3.2 on 2021-12-21 19:56

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.site')),
                ('get_price_from', models.CharField(choices=[('spot', 'Spot'), ('coincap', 'CoinCap')], default='spot', max_length=30)),
                ('access_id', models.CharField(max_length=150, null=True)),
                ('secret_key', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'settings',
                'db_table': 'core_settings',
            },
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
