# Generated by Django 3.2 on 2021-12-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='access_id',
            new_name='coinex_access_id',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='secret_key',
            new_name='coinex_secret_key',
        ),
    ]
